# Generated by Django 6.0.6 on 2026-06-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
