# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_add_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='photo_url',
        ),
    ]
