export { default as AdminLayout } from './AdminLayout'
export { default as AdminDashboard } from './AdminDashboard'
export { default as AdminPatients } from './AdminPatients'
export { default as AdminStaff } from './AdminStaff'
export { default as AdminAppointments } from './AdminAppointments'
export { default as AdminDoctors } from './AdminDoctors'
export { default as AdminSlots } from './AdminSlots'
